name: LeetCode Sync

on:
  schedule:
    # Run this workflow daily at midnight
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7
